# Site settings
title: xpush
email: xpush.io@gmail.com
description: "eXtensional PUSH : Real-time communication server"
baseurl: ""
url: "http://xpush.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
