# Site settings
title: xpush
email: xpush.io@gmail.com
description: "eXtensional PUSH : Real-time communication server"
baseurl: ""
url: "http://xpush.github.io"
github_username:  xpush

# Build settings
markdown: kramdown
permalink: none

paginate: 3
paginate_path: "blog/page:num"
