# Site settings
title: xpush
email: xpush.io@gmail.com
description: "eXtensional PUSH : Real-time communication server"
baseurl: ""
url: "http://xpush.github.io"
github_username:  xpush

# Build settings
markdown: kramdown
permalink: none

paginate: 3
paginate_path: "blog/page:num"


defaults:
  -
    scope:
      path: ""
    values:
      lang: ko
      layout: default
  -
    scope:
      path: en
    values:
      lang: en

collections :

  ko:
    name : "ko"
    url : "/"
  en:
    name : "en"
    url : "/en"

nav:
  ko:
    home:
      title: "HOME"
      url:   "/"
    about:
      title: "ABOUT"
      url:   "/about"
    documents:
      title: "DOCUMENTS"
      url:   "/doc"
    service:
      title: "SERVICES"
      url:   "/service"
    blog:
      title: "BLOG"
      url:   "/blog"
  en:
    home:
      title: "HOME"
      url:   "/"
    about:
      title: "ABOUT"
      url:   "/about"
    documents:
      title: "DOCUMENTS"
      url:   "/doc"
    service:
      title: "SERVICES"
      url:   "/service"
    blog:
      title: "BLOG"
      url:   "/blog"