# services

- name: messenger X
  images:
    - path: /service/single01.jpg
    - path: /service/single02.jpg
    - path: /service/single03.jpg
  description: <b>_data/servics.yml 작성해야 함</b><br> xpush 기반의 메신져 서비스 <br> 다양한 서비스와 연계 가능한 설치형 메신져 플랫폼으로, 기본 ....
  source: https://github.com/xpush/messengerX
  support: Android, IOS / Windows, OS X, Linux
  author: xpush team

- name: stalk.io
  images:
    - path: /service/single02.jpg
    - path: /service/single01.jpg
    - path: /service/single03.jpg
  description: <b>_data/servics.yml 작성해야 함</b><br> xpush 기반의 웹기반 대화 서비스
  url: http://stalk.io
  source: https://github.com/xpush/messengerX
  support: Any Web Browsers
  author: xpush team

- name: link.stalk.io
  images:
    - path: /service/single03.jpg
    - path: /service/single02.jpg
    - path: /service/single01.jpg
  description: <b>_data/servics.yml 작성해야 함</b><br> stalk.io 의 상담 서비스.
  url: http://link.stalk.io
  source: https://github.com/xpush/link.stalk.io
  support: Any Web Browsers
  author: xpush team
