# services

- name: messenger X
  images:
    - path: /lib/img/portfolio/single01.jpg
    - path: /lib/img/portfolio/single02.jpg
    - path: /lib/img/portfolio/single03.jpg
  description: xpush 기반의 메신져 서비스 <br> 다양한 서비스와 연계 가능한 설치형 메신져 플랫폼으로, 기본 ....
  source: https://github.com/xpush/messengerX
  support: Android, IOS / Windows, OS X, Linux

- name: stalk.io
  images:
    - path: /lib/img/portfolio/single02.jpg
    - path: /lib/img/portfolio/single01.jpg
    - path: /lib/img/portfolio/single03.jpg
  description: xpush 기반의 웹기반 대화 서비스
  url: http://stalk.io
  source: https://github.com/xpush/messengerX
  support: Android, IOS / Windows, OS X, Linux

- name: link.stalk.io
  images:
    - path: /lib/img/portfolio/single03.jpg
    - path: /lib/img/portfolio/single02.jpg
    - path: /lib/img/portfolio/single01.jpg
  description: stalk.io 의 상담 서비스.
  url: http://link.stalk.io
  source: https://github.com/xpush/link.stalk.io
  support: Android, IOS / Windows, OS X, Linux
